"""
Prompt 提示词聚合 — Agent 系统提示词定义
"""

from internal.prompt.prompt import (
    SYSTEM_PROMPT,
    TOOL_USE_PROMPT,
    MEMORY_LEVEL1_PROMPT,
    MEMORY_LEVEL2_PROMPT,
    CONTEXT_LEVEL2_TEMPLATE,
    CONTEXT_LEVEL1_TEMPLATE,
    CONTEXT_QUOTE_OLD_TEMPLATE,
    CONTEXT_QUOTE_RECENT_TEMPLATE
)

__all__ = [
    "SYSTEM_PROMPT",
    "TOOL_USE_PROMPT",
    "MEMORY_LEVEL1_PROMPT",
    "MEMORY_LEVEL2_PROMPT",
    "CONTEXT_LEVEL2_TEMPLATE",
    "CONTEXT_LEVEL1_TEMPLATE",
    "CONTEXT_QUOTE_OLD_TEMPLATE",
    "CONTEXT_QUOTE_RECENT_TEMPLATE"
]
